services:
  api:
    container_name: telegraph_test_api
    environment: 
      - DB_NAME=posts_test
      - DB_CONNECTION=mongodb://telegraphuser:telegraphpass@db:27017
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: telegraph_test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=telegraphuser
      - MONGO_INITDB_DATABASE=posts_test
      - MONGO_INITDB_ROOT_PASSWORD=telegraphpass
volumes:
  test_db:
networks: 
  default:
    name: telegraph_test